MyApp2/urls.py
from django.conf.urls import url, include
from .views import index
from .views import add_status
from .views import profil
from .views import booklist_index
from .views import get_mybooks
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_status', add_status, name='add_status'),
    url(r'^profil', profil, name='profil'),
    url(r'^booklist', booklist_index, name='mybooklist'),
    url(r'^bookdata', get_mybooks, name='mybookdata'),
]

PPWProject2/PPWProject2/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

lab_1/urls.py
from django.urls import re_path
from .views import index
#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
]

lab_2/urls.py
from django.urls import path
from .views import index

#url for app, add your URL Configuration

urlpatterns = [
#TODO Implement this
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.contrib import admin
from lab_1.views import index as index_lab1
import MyApp2.urls as MyApp2


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^lab-1/', include('lab_1.urls')),
    re_path(r'^lab-2/', include('lab_2.urls')),
	re_path(r'^MyApp2/', include(('MyApp2.urls', 'MyApp2'), namespace='MyApp2')),
]

MyApp2/models.py
from django.db import models 

# Create your models here.
class status(models.Model):
	description = models.TextField(max_length=300)
	created_date = models.DateTimeField(auto_now_add=True)

lab_1/models.py
from django.db import models

# Create your models here.

lab_2/models.py
from django.db import models

# Create your models here.

MyApp2/forms.py
from django import forms

class status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }

    description_attrs = {
        'type': 'text',
        'placeholder':'What is in your mind?'
    }

    description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

MyApp2/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from .models import status
from .forms import status_Form
import requests

# Create your views here.
response={}

def index(request):
    response['stats'] = status_Form
    response['status'] = status.objects.all()
    html = 'index.html'
    return render(request, html, response)


def add_status(request):
    form = status_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['description'] = request.POST['description']
        a = status(description=response['description'])
        a.save()
        return HttpResponseRedirect('/MyApp2/')
    else:
        return HttpResponseRedirect('/MyApp2/')

def profil(request):
    return render(request, 'profil.html')

def booklist_index(request):
	return render(request, "booklist.html", response)

def get_mybooks(request):
	q = request.GET.get('q', '')
	API_MYBOOK = "https://www.googleapis.com/books/v1/volumes?q=" + q
	book = requests.get(API_MYBOOK).json()
	return JsonResponse(book)

lab_1/views.py
from django.shortcuts import render
from datetime import datetime, date
# Enter your name here
mhs_name = 'Hana Dior Novelyne Tobing'
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(1999, 11, 29) #TODO Implement this, format (Year, Month, Date)
npm = 1706025182 # TODO Implement this
# Create your views here.
def index(request):
    response = {'name': mhs_name, 'age': calculate_age(birth_date.year), 'npm': npm}
    return render(request, 'index_lab1.html', response)

def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0

lab_2/views.py
from django.shortcuts import render
from lab_1.views import mhs_name, birth_date

#TODO Implement
#Create a content paragraph for your landing page:
landing_page_content = ''

def index(request):
    response = {'name': mhs_name, 'content': landing_page_content}
    return render(request, 'index_lab2.html', response)

MyApp2/templates/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>OceanEscape</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1 shrink-to-fit=no">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
	<script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
	<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
	<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/v4-shims.js"></script>
	<script src="{% static 'MyApp2/script.js' %}"></script>
	<link rel="stylesheet" type="text/css" href={% static "MyApp2/style.css" %}>
	<link href='https://fonts.googleapis.com/css?family=Prata' rel='stylesheet'>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
</head>

<body>
<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
	<div class="container-fluid">
		<a class="navbar-logo rounded-circle" href=".."><img src="https://scontent.fcgk4-2.fna.fbcdn.net/v/t1.0-9/42743592_544158646036454_4740123858613305344_n.jpg?_nc_cat=107&oh=3b780162c89fed8b3b958cace2384b5d&oe=5C235A52" style="display : inline-block" width="80" height="80"></a>
		{% include 'navbar.html'%}
	</div>
</nav>
{% block content %}{% endblock %}
</body>

<footer>
    <!-- TODO Block Footer dan include footer.html -->
    {% block footer %}
    {% include "footer.html" %}
    {% endblock %}
</footer>

</html>

MyApp2/templates/footer.html
<div class="footer" style="background-color: #FFFFFF">
	<br>
	<div class="row">
		<div class="col-md-1 mb-md-0 mb-1">
			 <img class="responsive" src="https://image.flaticon.com/icons/svg/69/69366.svg">
		</div>
		<div class="col-md-1 mb-md-0 mb-1">
			 <img class="responsive" src="https://image.flaticon.com/icons/svg/69/69480.svg">
		</div>
	</div>
</div>

MyApp2/templates/index.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>OceanEscape</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1 shrink-to-fit=no">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
	<script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
	<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
	<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/v4-shims.js"></script>
	<script src="{% static 'MyApp2/script.js' %}"></script>
	<link rel="stylesheet" type="text/css" href={% static "MyApp2/style.css" %}>
	<link href='https://fonts.googleapis.com/css?family=Prata' rel='stylesheet'>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
</head>

<body onload="myFunction()" style="margin:0;">
	<div id="loader"></div>
	<div style="display:none;" id="myDiv" class="animate-bottom">
		<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
		<div class="container-fluid">
			<a class="navbar-logo rounded-circle" href=".."><img src="https://scontent.fcgk4-2.fna.fbcdn.net/v/t1.0-9/42743592_544158646036454_4740123858613305344_n.jpg?_nc_cat=107&oh=3b780162c89fed8b3b958cace2384b5d&oe=5C235A52" style="display : inline-block" width="80" height="80"></a>
			{% include 'navbar.html'%}
		</div>
		</nav>
		<h1>Hello, good people!</h1>
		<button class="nightbutton">Night View</button>
		<hr/>
		<div class="container">
			<div class="myform">
				<form id="form" method="POST" action="{% url 'MyApp2:add_status' %}">
					<h2>Enter your status here</h2>
					{% csrf_token %}
					{{ stats }}
					<input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
					<br>
				</form>
			</div>
		</div>


		<div style="margin: 5% 5%">
			<h2>My Status</h2>
			<div style = "width: 80%">
				<table class="table" border="#0000" style="width: 100% margin: 0 0;">
					<tr background-color="#ffff">
					<th style="width: 50%">Status</th>
					<th style="width: 50%">Date</th>
				   </tr>
				   {%for e in status%}
				   <tr background-color=#ffff>
					<td>{{e.description}}</td>
					<td>{{e.created_date}}</td>
				   </tr>
				   {%endfor%}
				</table>
			</div>
		</div>

		<h2>More about me</h2>
		<br>
		<button class="accordion">My Activities</button>
		<div class="panel">
		  <p>Mangan<br>Turu<br>Mencoba Lulus</p>
		</div>

		<button class="accordion">My Experiences</button>
		<div class="panel">
		  <p>Volunteering</p>
		</div>

		<button class="accordion">My Achievements</button>
		<div class="panel">
		  <p>lol, maybe in another life</p>
		</div>
		<footer>
		<!-- TODO Block Footer dan include footer.html -->
		{% block footer %}
		{% include "footer.html" %}
		{% endblock %}
		</footer>
	</div>
	
</body>
</html>

MyApp2/templates/navbar.html
{% load static %}
{% block content %}
<ul class="navbar-nav ml-auto">
			<li class="nav-item active">
				<a class="nav-link" href="{% url 'MyApp2:index' %}">Home</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'MyApp2:profil' %}">About</a>
			</li>
</ul>
{% endblock %}

MyApp2/templates/profil.html
{% extends "base.html" %}
{% block content %}
<div class="split left">
  <div class="centered">
    <img src="https://scontent.fcgk4-2.fna.fbcdn.net/v/t1.0-9/42635985_544158369369815_1603846130989268992_n.jpg?_nc_cat=108&oh=c4256a34b01cc37483d4571b61e4ac31&oe=5C226924" alt="photo of hana">
    <h1>Dramatic.<br>Traumatic.<br>Sarcastic.</h1>
  </div>
</div>

<div class="split right">
  <div class="centered">
    <h2>As the years go by ...</h2>
    <p>
		'99 : Was born in Bogor<br>
		'05 : Entered SD Kesatuan Bogor<br>
		'11 : Entered SMPN 2 Bogor<br>
		'14 : Entered SMAN 1 Bogor<br>
		'17 : Entered University of Indonesia<br>
		'18 : Became Asian Games Volunteer
	</p>
	<h2>A little insight about me ...</h2>
	<p>
		My hometown is in Bogor<br>
		My passion are cooking and gardening<br>
		I hope you can get to know me better!
	</p>
  </div>
</div>
{% endblock %}
</html>

lab_1/templates/index_lab1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ name }}</title>
</head>
<body>
    <h1>Hello my name is {{ name }}</h1>
    <article>NPM : {{ npm }}</article>
    <article>I am {{ age }} years old</article>
</body>
</html>

lab_2/templates/description_lab2addon.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Biodata</title>
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<body style="background-color: aqua">
    <h3 style="text-align: center">Hi all, This is my complete biodata</h3>
    <table align="center" style="text-align: center">
        {% for bio in bio_dict %}
            <tr>
                <td class="subject">{{ bio.subject }}</td>
                <td class="value">{{ bio.value }}</td>
            </tr>
        {% endfor %}
    </table>
    <br><br>
</body>

</html>

lab_2/templates/index_lab2.html
{% extends "base.html" %}
{% block content %}
<style>
    .center_screen {
        position: absolute;
        width: 500px;
        height: 50px;
        top: 50%;
        left: 50%;
        margin-left: -250px; /* margin is -0.5 * dimension */
        margin-top: -25px;
    }
</style>
<div class="center_screen">
    <p class="status" id="test">Hello, this is {{ name }}. {{ content }}.</p>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Biodata</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<body style="background-color: lightgray">
    <div class="container-fullwidth">
        <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/lab-2/">Home</a>
              </li>
              <li class="nav-item" >
                <a class="nav-link" href="/lab-2-addon/">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/lab-3/">Diary</a>
              </li>
            </ul>
          </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
{% block jquery %}
{% endblock %}
</html>

templates/description_lab2addon.html
{% extends "base.html" %}
{% block content %}
<h3 style="text-align: center">Hi all, This is my complete biodata</h3>
<table align="center" style="text-align: center">
    {% for bio in bio_dict %}
        <tr>
            <td class="subject">{{ bio.subject }}</td>
            <td class="value">{{ bio.value }}</td>
        </tr>
    {% endfor %}
</table>
<br><br>
{% endblock %}

templates/to_do_list.html
{% extends "base.html" %}
{% block content %}
<h3 style="text-align: center">Hai semua, berikut adalah Catatan Harianku</h3>
<br><br>
<div class="row">
    <div class="col-md-6 col-xs-6">
        <table align="center" style="text-align: center">
            <tr>
                <th>Tanggal</th>
                <th>Yang akan dikerjakan</th>
            </tr>
            {% for diary_data in diary_dict %}
                <tr>
                    <td class="date">{{ diary_data.date }}</td>
                    <td class="activity">{{ diary_data.activity }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="col-md-6 col-xs-6">
        <form method="POST" action="add_activity/">
            {% csrf_token %}
            <table>
                <tr>
                    <td>
                        Tanggal
                    </td>
                    <td>
                        <input type="datetime-local" name="date" id="date" required="required"/>
                    </td>
                </tr>
                <tr>
                    <td>
                        Kegiatan
                    </td>
                    <td>
                        <input type="text" name="activity" id="activity" size="25"/>
                    </td>
                </tr>
            </table>
            <button type="submit" class="button btn-success">Submit</button>
        </form>
    </div>
</div>
{% endblock %}